name: Build on Mac
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: brew install boost freetype libpng sdl2 pkgconfig nasm
      - name: Build mupen64plus
        run: cd projects/unix && make all
